# --- Site Settings ---
title: Mendelevium
tagline: A blog on MD simulations, chemoinformatics, and more.
description: >-
  Mendelevium is a personal blog sharing my research and life experiences. I will write about MD simulations, chemoinformatics, Linux, basic tools. I will also share my thoughts on web scraping, web development, machine learning, and so on.

# GitHub Pages settings
url: "https://gxf1212.github.io" 
baseurl: "/mendelevium" 

# --- Author Info ---
author: Xufan Gao
location: "Hangzhou, Zhejiang, China"
affiliation: "Zhejiang University (ZJU)"

# --- Social Links ---
social:
  name: Xufan Gao
  email: gxf1212@zju.edu.cn
  links:
    - https://github.com/gxf1212/
    - https://twitter.com/XufanGao
    - https://scholar.google.com/citations?hl=en&user=f8pi1BUAAAAJ
    - https://gxf1212.github.io/notes/#/
    - https://space.bilibili.com/441196634
    - https://www.zhihu.com/people/wo-zhen-de-hao-cai-a

logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"

# Social Links
email: gxf1212@zju.edu.cn
github_username: gxf1212
twitter_username: Gaoxufan

# External API
giscus_repo: "gxf1212/mendelevium"
giscus_repoId: "MDEwOlJlcG9zaXRvcnk3MzY2MzAyOTA="
giscus_category: "General"
giscus_categoryId: "DIC_kwDOKdHdGs4CiA-m"
goatcounter_code: "gxf1212-mendelevium"
google_analytics: ""

# Build settings for GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist

# Pagination
paginate: 5
paginate_path: "/page:num/"

exclude:
  - docs/
  - old/
  - _pages/archive/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - "*.gemspec"
  - README.md
  - LICENSE

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
