# _config.yml (Corrected Version)

# Site settings
title: Mendelevium
email: gxf1212@zju.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
  Mendelevium is a personal blog sharing my research and life experiences. I will write about MD simulations, chemoinformatics, Linux, basic tools. I will also share my thoughts on web scraping, web development, machine learning, and so on.

# GitHub Pages settings for a Project Page
# The url is your main GitHub Pages domain.
# The baseurl is the name of your repository.
url: "https://gxf1212.github.io" 
baseurl: "/mendelevium" 

twitter_username: XufanGao
github_username:  gxf1212
timezone: Asia/Shanghai

# Build settings
# This MUST match the theme specified in your Gemfile.
theme: minima
plugins:
  - jekyll-feed
show_excerpts: true

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # Exclusions to prevent build errors from non-post files
  - "**/*.docx"
  - "**/*.pdf"
  - "**/*.aux"
  - "**/*.synctex.gz"
  - "_posts/try/"