# --- Site Settings ---
title: Mendelevium
tagline: A blog on MD simulations, chemoinformatics, and more.
description: >-
  Mendelevium is a personal blog sharing my research and life experiences. I will write about MD simulations, chemoinformatics, Linux, basic tools. I will also share my thoughts on web scraping, web development, machine learning, and so on.
# The url and baseurl are configured for your GitHub Pages project site.
url: "https://gxf1212.github.io" 
baseurl: "/mendelevium" 

# --- Author Info ---
author: Xufan Gao
# You can add your avatar image here. Place the image in /assets/img/
# avatar: "/assets/img/my-avatar.jpg"

# --- Social Links ---
social:
  name: Xufan Gao
  email: gxf1212@zju.edu.cn
  links:
    - https://twitter.com/XufanGao
    - https://github.com/gxf1212
    # - https://space.bilibili.com/441196634

# --- Build Settings ---
# Use the 'remote_theme' directive instead of 'theme' for GitHub Pages.
remote_theme: cotes2020/jekyll-theme-chirpy@latest

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-last-modified-at
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-remote-theme # Make sure this plugin is listed

# --- Theme-Specific Settings (Chirpy) ---
lang: en 
timezone: Asia/Shanghai
theme_mode: light 
img_cdn: ""

# Sidebar customization
sidebar:
  home_show: true
  tabs_order: [ "nav", "categories", "tags" ] 

# Table of Contents (TOC) settings
toc:
  enable: true
  class: "post-content"
  min_headings: 2
  depth: 2

# Comments settings (e.g., Disqus, Utterances, Giscus)
comments:
  provider: # "disqus", "utterances", "giscus"

# --- Other Settings ---
paginate: 10
paginate_path: "/page:num/"

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "**/*.docx"
  - "**/*.pdf"
  - "**/*.aux"
  - "**/*.synctex.gz"
  - "_posts/try/"